package a;

public class Trycatchfinal {
	public static void main(String args[])
	{
		int[] arr = new int[4];
		try
		{
			int i = arr[3];
			System.out.println("inside try block");
			
		}
		Catch(ArrayIndexOutOfBoundsException e)
		{
			
		}
		
	}

}
